### ISSUE TITLE
Icon not working

### ISSUE THREAD

**Issue by Freak871** [Naru-kami/BackgroundManager-plugin#8]
I am trying to press the Icon to add an new image but the menu is not popping up

**Comment by PiizaTime** [comment]
I'm having the same issue, the button for the menu at the top right doesn't do anything right now

**Comment by Naru-kami** [comment]
This seems to be positioning issue of the popout component. Until I figure out what Discord did to the popout, you can fix it with some customCSS:
```css
.layer_da8173:has(.BackgroundManager-inputWrapper) {
  right: 1rem !important;
  top: 6rem !important;
}
```
